name: Build project

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  cancel-previous-workflows:
    name: Cancel previous workflow runs
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - uses: gradle/gradle-build-action@v2

      - name: Code style check
        run: ./gradlew projectCodestyle --stacktrace

      - run: ./gradlew assemble --stacktrace

      - run: ./gradlew validatePlugins --stacktrace

      - run: ./gradlew projectCoverage --stacktrace

      - uses: codecov/codecov-action@v3

      - name: Upload test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: "${{ github.workspace }}/**/build/reports/tests"

      - name: Upload jacoco report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: "${{ github.workspace }}/**/build/reports/jacoco"

  build-all-sample-apps:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        javaVersion: [ 17 ]
        gradle: [ current, release-candidate ]
        agp: [ 7.2.1, 7.4.0-alpha03 ]
        include:
          - javaVersion: 11
            gradle: 6.5
            agp: 4.1.0
          - javaVersion: 11
            gradle: 6.7.1
            agp: 4.1.0
          - javaVersion: 11
            gradle: 7.0.2
            agp: 7.0.4
          - javaVersion: 11
            gradle: 7.3.3
            agp: 7.0.4
          - javaVersion: 17
            gradle: 7.4
            agp: 7.0.4

    name: Run Gradle-${{ matrix.gradle }}, AGP-${{ matrix.agp }}, Java-${{ matrix.javaVersion }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.javaVersion }}

      - uses: gradle/gradle-build-action@v2

      - name: Pre-compile plugin
        run: ./gradlew publishToMavenLocal -Pgroup=com.project.starter.local

      - uses: gradle/gradle-build-action@v2
        with:
          build-root-directory: sample
          gradle-version: ${{ matrix.gradle }}
          arguments: assemble lint -PuseMavenLocal -PagpVersion=${{ matrix.agp }} --stacktrace

  build-sample-apps-with-confgiuration-cache:
    runs-on: ${{ matrix.os }}
    name: Configuration Cache Java-${{ matrix.javaVersion }} OS-${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        javaVersion: [ 11, 17 ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.javaVersion }}

      - name: Pre-compile plugin
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publishToMavenLocal -Pgroup=com.project.starter.local

      - uses: gradle/gradle-build-action@v2
        with:
          build-root-directory: sample
          gradle-version: current
          arguments: assembleDebug --configuration-cache --stacktrace

  icons-test:
    runs-on: macos-latest
    strategy:
      matrix:
        apiVersion: [ 28 ]

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - uses: gradle/gradle-build-action@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade Pillow

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.apiVersion }}
          profile: pixel_xl
          target: google_apis
          arch: x86
          disable-spellchecker: true
          script: cd sample && ./icon_check.sh

      - name: Upload failed screenshots
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: failedScreenshots
          path: "${{ github.workspace }}/**/build/failedScreenshots"

      - name: Upload screenshot tests result
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: "${{ github.workspace }}/**/build/*AndroidTest/"
