name: Publish Project to Gradle Plugin Portal

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'usefulness/easylauncher-gradle-plugin'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - uses: gradle/gradle-build-action@v2

      - name: Build app with Gradle
        run: ./gradlew assemble

      - name: Publish to Gradle Plugin Portal
        run: ./gradlew publishPlugins -Pgradle.publish.key=${{ secrets.gradle_publish_key }} -Pgradle.publish.secret=${{ secrets.gradle_publish_secret }}

      - name: Publish to Github Package Registry
        run: ./gradlew publish --continue || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
